# Generated by Django 2.0.1 on 2020-03-02 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0003_auto_20200301_2152'),
    ]

    operations = [
        migrations.AlterField(
            model_name='answer',
            name='text',
            field=models.CharField(max_length=255, null=True, verbose_name='Answer'),
        ),
    ]
