# Generated by Django 2.0.1 on 2020-03-02 15:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0004_auto_20200302_0451'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='data',
        ),
        migrations.RemoveField(
            model_name='question',
            name='is_active',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='submission',
        ),
    ]
