# Generated by Django 2.0.1 on 2020-03-02 16:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_auto_20200302_1601'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='data',
        ),
        migrations.RemoveField(
            model_name='studentanswer',
            name='submission',
        ),
    ]
