# Generated by Django 2.0.1 on 2020-02-25 20:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0006_course_code'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course',
            name='code',
            field=models.CharField(default=False, max_length=255, unique=True),
        ),
    ]
