# Generated by Django 2.0.1 on 2020-03-02 22:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_auto_20200302_1812'),
    ]

    operations = [
        migrations.AddField(
            model_name='question',
            name='is_active',
            field=models.BooleanField(default=False, verbose_name='Active'),
        ),
    ]
