# Generated by Django 2.0.1 on 2020-03-03 04:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0009_question_is_active'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='answer',
            name='is_correct',
        ),
        migrations.RemoveField(
            model_name='answer',
            name='text',
        ),
    ]
