# Generated by Django 2.0.1 on 2020-03-03 04:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0010_auto_20200303_0433'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='studentanswer',
            name='answer',
        ),
        migrations.AddField(
            model_name='studentanswer',
            name='question',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='classroom.Question'),
        ),
    ]
