# Generated by Django 2.0.1 on 2020-02-25 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('classroom', '0008_auto_20200225_2016'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='courses',
            field=models.ManyToManyField(related_name='student_courses', to='classroom.Course'),
        ),
    ]
